import type { LocalizedText } from './menu.types';

const MENU_NAME_TRANSLATIONS: Readonly<Record<string, LocalizedText>> = {
  'Iced Americano': { uz: 'Muzli Americano', ru: 'Айс-американо', en: 'Iced Americano' },
  'Iced Latte': { uz: 'Muzli latte', ru: 'Айс-латте', en: 'Iced Latte' },
  Frappe: { uz: 'Frappe', ru: 'Фраппе', en: 'Frappe' },
  'Bumble Orange': { uz: 'Bumble Orange', ru: 'Bumble Orange', en: 'Bumble Orange' },
  'Iced Chocolate': { uz: 'Muzli shokolad', ru: 'Айс-шоколад', en: 'Iced Chocolate' },
  'Iced Cappucino': { uz: 'Muzli kapuchino', ru: 'Айс-капучино', en: 'Iced Cappucino' },
  'Berry Presso': { uz: 'Berry Presso', ru: 'Berry Presso', en: 'Berry Presso' },
  'Spanish Latte': { uz: 'Ispancha latte', ru: 'Испанский латте', en: 'Spanish Latte' },
  Espresso: { uz: 'Espresso', ru: 'Эспрессо', en: 'Espresso' },
  Americano: { uz: 'Americano', ru: 'Американо', en: 'Americano' },
  Latte: { uz: 'Latte', ru: 'Латте', en: 'Latte' },
  Cappuccino: { uz: 'Kapuchino', ru: 'Капучино', en: 'Cappuccino' },
  'Flat White': { uz: 'Flat white', ru: 'Флэт уайт', en: 'Flat White' },
  'Raf Coffe': { uz: 'Raf coffee', ru: 'Раф кофе', en: 'Raf Coffe' },
  'Raspberry Raf': { uz: 'Malinali raf', ru: 'Малиновый раф', en: 'Raspberry Raf' },
  Mocha: { uz: 'Mokko', ru: 'Мокка', en: 'Mocha' },
  'Ginger Latte': { uz: 'Zanjabilli latte', ru: 'Имбирный латте', en: 'Ginger Latte' },
  'Classic (Black/Green/Lemon/Jasmine)': {
    uz: 'Klassik (qora/yashil/limon/yasmin)',
    ru: 'Классический (чёрный/зелёный/лимонный/жасминовый)',
    en: 'Classic (Black/Green/Lemon/Jasmine)',
  },
  'Berry Tea (Tea Pot)': {
    uz: 'Rezavorli choy (choynak)',
    ru: 'Ягодный чай (чайник)',
    en: 'Berry Tea (Tea Pot)',
  },
  'Ginger & Sea Buckthorn Tea': {
    uz: 'Zanjabil va chakanda choyi',
    ru: 'Чай с имбирём и облепихой',
    en: 'Ginger & Sea Buckthorn Tea',
  },
  'Mango Passion Fruit Tea (Tea Pot)': {
    uz: 'Mango va marakuya choyi (choynak)',
    ru: 'Чай с манго и маракуйей (чайник)',
    en: 'Mango Passion Fruit Tea (Tea Pot)',
  },
  'Morrocan Tea (Tea Pot)': {
    uz: 'Marokash choyi (choynak)',
    ru: 'Марокканский чай (чайник)',
    en: 'Morrocan Tea (Tea Pot)',
  },
  'Citrus Tea (Tea Pot)': {
    uz: 'Sitrus choyi (choynak)',
    ru: 'Цитрусовый чай (чайник)',
    en: 'Citrus Tea (Tea Pot)',
  },
  'Green Lemon Tea (Tea Pot)': {
    uz: 'Yashil limon choyi (choynak)',
    ru: 'Зелёный чай с лимоном (чайник)',
    en: 'Green Lemon Tea (Tea Pot)',
  },
  'Black Lemon Tea (Tea Pot)': {
    uz: 'Qora limon choyi (choynak)',
    ru: 'Чёрный чай с лимоном (чайник)',
    en: 'Black Lemon Tea (Tea Pot)',
  },
  'Coconut Milk': { uz: 'Kokos suti', ru: 'Кокосовое молоко', en: 'Coconut Milk' },
  'Oat Milk': { uz: 'Suli suti', ru: 'Овсяное молоко', en: 'Oat Milk' },
  'Almond Milk': { uz: 'Bodom suti', ru: 'Миндальное молоко', en: 'Almond Milk' },
  'Lactose Free Milk': { uz: 'Laktozasiz sut', ru: 'Безлактозное молоко', en: 'Lactose Free Milk' },
  'Strawberry Jasmine Iced Tea': {
    uz: 'Qulupnayli yasmin muzli choyi',
    ru: 'Холодный жасминовый чай с клубникой',
    en: 'Strawberry Jasmine Iced Tea',
  },
  'Mango Passion Fruit Lemonade': {
    uz: 'Mango va marakuyali limonad',
    ru: 'Лимонад с манго и маракуйей',
    en: 'Mango Passion Fruit Lemonade',
  },
  'Mixed Berry Lemonade': {
    uz: 'Aralash rezavorli limonad',
    ru: 'Лимонад с лесными ягодами',
    en: 'Mixed Berry Lemonade',
  },
  'Classic Mojito': { uz: 'Klassik mojito', ru: 'Классический мохито', en: 'Classic Mojito' },
  'Tarragon Drink': { uz: 'Estragon ichimligi', ru: 'Напиток с эстрагоном', en: 'Tarragon Drink' },
  'Citrus Drink': { uz: 'Sitrus ichimligi', ru: 'Цитрусовый напиток', en: 'Citrus Drink' },
  'Matcha Mango': { uz: 'Mango matcha', ru: 'Матча с манго', en: 'Matcha Mango' },
  'Matcha Strawberry': {
    uz: 'Qulupnayli matcha',
    ru: 'Матча с клубникой',
    en: 'Matcha Strawberry',
  },
  'Matcha Passion Fruit': {
    uz: 'Marakuyali matcha',
    ru: 'Матча с маракуйей',
    en: 'Matcha Passion Fruit',
  },
  'Matcha Latte': { uz: 'Matcha latte', ru: 'Матча-латте', en: 'Matcha Latte' },
  'Lemonade (Green/Pink)': {
    uz: 'Limonad (yashil/pushti)',
    ru: 'Лимонад (зелёный/розовый)',
    en: 'Lemonade (Green/Pink)',
  },
  'Mango Latte': { uz: 'Mango latte', ru: 'Манговый латте', en: 'Mango Latte' },
  'Berry Milkshakes': {
    uz: 'Rezavorli milkshake',
    ru: 'Ягодный молочный коктейль',
    en: 'Berry Milkshakes',
  },
  'Vanilla Milkshake': {
    uz: 'Vanilli milkshake',
    ru: 'Ванильный молочный коктейль',
    en: 'Vanilla Milkshake',
  },
  'Chocolate Milkshake': {
    uz: 'Shokoladli milkshake',
    ru: 'Шоколадный молочный коктейль',
    en: 'Chocolate Milkshake',
  },
  'Orange Fresh Juice': {
    uz: 'Yangi apelsin sharbati',
    ru: 'Свежий апельсиновый сок',
    en: 'Orange Fresh Juice',
  },
  'Apple Fresh Juice': {
    uz: 'Yangi olma sharbati',
    ru: 'Свежий яблочный сок',
    en: 'Apple Fresh Juice',
  },
  'Carrot Fresh Juice': {
    uz: 'Yangi sabzi sharbati',
    ru: 'Свежий морковный сок',
    en: 'Carrot Fresh Juice',
  },
  'Apple & Carrot Juice': {
    uz: 'Olma va sabzi sharbati',
    ru: 'Яблочно-морковный сок',
    en: 'Apple & Carrot Juice',
  },
  'Apple & Celery Detox': {
    uz: 'Olma va selderey detoks',
    ru: 'Детокс с яблоком и сельдереем',
    en: 'Apple & Celery Detox',
  },
  'Chocolate Bomboloni': {
    uz: 'Shokoladli bomboloni',
    ru: 'Шоколадный бомболони',
    en: 'Chocolate Bomboloni',
  },
  'Jam & Manila Bomboloni': {
    uz: 'Murabbo va Manila bomboloni',
    ru: 'Бомболони с джемом и манилой',
    en: 'Jam & Manila Bomboloni',
  },
  'Nutella Donuts': { uz: 'Nutellali ponchiklar', ru: 'Пончики с Nutella', en: 'Nutella Donuts' },
  'Bomboloni Raspberry': {
    uz: 'Malinali bomboloni',
    ru: 'Малиновый бомболони',
    en: 'Bomboloni Raspberry',
  },
  'Rafaello Croissant': {
    uz: 'Rafaello kruassani',
    ru: 'Круассан Rafaello',
    en: 'Rafaello Croissant',
  },
  'New York Roll Rafaello': {
    uz: 'Rafaello New York roll',
    ru: 'New York roll Rafaello',
    en: 'New York Roll Rafaello',
  },
  'Chocolate Croissant': {
    uz: 'Shokoladli kruassan',
    ru: 'Шоколадный круассан',
    en: 'Chocolate Croissant',
  },
  'Fistachio Croissant': {
    uz: 'Pistali kruassan',
    ru: 'Фисташковый круассан',
    en: 'Fistachio Croissant',
  },
  'Cruffin Caramel Vanilla': {
    uz: 'Karamel-vanilli kruffin',
    ru: 'Круффин с карамелью и ванилью',
    en: 'Cruffin Caramel Vanilla',
  },
  'Chocolate Cruffin': {
    uz: 'Shokoladli kruffin',
    ru: 'Шоколадный круффин',
    en: 'Chocolate Cruffin',
  },
  'Cruffin Raspberry': { uz: 'Malinali kruffin', ru: 'Малиновый круффин', en: 'Cruffin Raspberry' },
  'Nutella Danish': { uz: 'Nutellali danish', ru: 'Даниш с Nutella', en: 'Nutella Danish' },
  'Fruit Danish': { uz: 'Mevali danish', ru: 'Фруктовый даниш', en: 'Fruit Danish' },
  'Izum Danish': { uz: 'Izum danish', ru: 'Даниш Izum', en: 'Izum Danish' },
  'Danish with Jam': { uz: 'Murabbali danish', ru: 'Даниш с джемом', en: 'Danish with Jam' },
  'Nasi Goreng': { uz: 'Nasi goreng', ru: 'Наси горенг', en: 'Nasi Goreng' },
  'Sate Kambing': { uz: 'Sate kambing', ru: 'Сате камбинг', en: 'Sate Kambing' },
  'Soto Ayam': { uz: 'Soto ayam', ru: 'Сото ая́м', en: 'Soto Ayam' },
  'Beef Rendang': { uz: 'Mol go‘shtli rendang', ru: 'Ренданг из говядины', en: 'Beef Rendang' },
  'Ayam Bakar': { uz: 'Ayam bakar', ru: 'Аям бакар', en: 'Ayam Bakar' },
  'Mie Goreng': { uz: 'Mie goreng', ru: 'Ми горенг', en: 'Mie Goreng' },
  'Gado-Gado': { uz: 'Gado-gado', ru: 'Гадо-гадо', en: 'Gado-Gado' },
  Bakso: { uz: 'Bakso', ru: 'Баксо', en: 'Bakso' },
  'Nyuknyang Makassar': {
    uz: 'Nyuknyang Makassar',
    ru: 'Нюкнянг Макассар',
    en: 'Nyuknyang Makassar',
  },
  Lumpia: { uz: 'Lumpia', ru: 'Лумпия', en: 'Lumpia' },
  'Martabak Telur': { uz: 'Martabak telur', ru: 'Мартабак с яйцом', en: 'Martabak Telur' },
  'Tempe Mendoan': { uz: 'Tempe mendoan', ru: 'Темпе мендоан', en: 'Tempe Mendoan' },
  'Pisang Goreng': { uz: 'Pisang goreng', ru: 'Писанг горенг', en: 'Pisang Goreng' },
  'Es Cendol': { uz: 'Es cendol', ru: 'Эс чендол', en: 'Es Cendol' },
  'Teh Poci': { uz: 'Teh poci', ru: 'Чай teh poci', en: 'Teh Poci' },
  'Es Jeruk': { uz: 'Es jeruk', ru: 'Эс джерук', en: 'Es Jeruk' },
  'Kopi Tubruk': { uz: 'Kopi tubruk', ru: 'Копи тубрук', en: 'Kopi Tubruk' },
  'Wedang Jahe': { uz: 'Wedang jahe', ru: 'Веданг джае', en: 'Wedang Jahe' },
  'Traditional Massage': {
    uz: 'An’anaviy massaj',
    ru: 'Традиционный массаж',
    en: 'Traditional Massage',
  },
  'Relaxation Massage': {
    uz: 'Relaks massaj',
    ru: 'Расслабляющий массаж',
    en: 'Relaxation Massage',
  },
  'Aromatherapy Massage': {
    uz: 'Aromaterapiya massaji',
    ru: 'Ароматерапевтический массаж',
    en: 'Aromatherapy Massage',
  },
  'Deep Tissue Massage': {
    uz: 'Chuqur to‘qima massaji',
    ru: 'Массаж глубоких тканей',
    en: 'Deep Tissue Massage',
  },
  'Foot Massage': { uz: 'Oyoq massaji', ru: 'Массаж ног', en: 'Foot Massage' },
  'Head & Shoulder Massage': {
    uz: 'Bosh va yelka massaji',
    ru: 'Массаж головы и плеч',
    en: 'Head & Shoulder Massage',
  },
  'Body Scrub': { uz: 'Tana skrabi', ru: 'Скраб для тела', en: 'Body Scrub' },
  'Body Treatment': { uz: 'Tana parvarishi', ru: 'Уход за телом', en: 'Body Treatment' },
  'Facial Treatment': { uz: 'Yuz parvarishi', ru: 'Уход за лицом', en: 'Facial Treatment' },
  'Couple Treatment': {
    uz: 'Juftlik parvarishi',
    ru: 'Процедура для пары',
    en: 'Couple Treatment',
  },
  'Other SPA Request': {
    uz: 'Boshqa SPA so‘rovi',
    ru: 'Другой запрос SPA',
    en: 'Other SPA Request',
  },
  'Room Cleaning': { uz: 'Xonani tozalash', ru: 'Уборка номера', en: 'Room Cleaning' },
  'Laundry Service': { uz: 'Kir yuvish xizmati', ru: 'Услуга прачечной', en: 'Laundry Service' },
  'Ironing Service': { uz: 'Dazmollash xizmati', ru: 'Услуга глажки', en: 'Ironing Service' },
  'Extra Towel': { uz: 'Qo‘shimcha sochiq', ru: 'Дополнительное полотенце', en: 'Extra Towel' },
  'Extra Pillow': { uz: 'Qo‘shimcha yostiq', ru: 'Дополнительная подушка', en: 'Extra Pillow' },
  'Extra Blanket': { uz: 'Qo‘shimcha adyol', ru: 'Дополнительное одеяло', en: 'Extra Blanket' },
  'Toiletries Request': {
    uz: 'Gigiyena vositalari so‘rovi',
    ru: 'Запрос туалетных принадлежностей',
    en: 'Toiletries Request',
  },
  'Drinking Water Request': {
    uz: 'Ichimlik suvi so‘rovi',
    ru: 'Запрос питьевой воды',
    en: 'Drinking Water Request',
  },
  'Trash Collection': { uz: 'Chiqindilarni yig‘ish', ru: 'Сбор мусора', en: 'Trash Collection' },
  'Room Amenity Request': {
    uz: 'Xona jihozlari so‘rovi',
    ru: 'Запрос удобств для номера',
    en: 'Room Amenity Request',
  },
  'Other Housekeeping Request': {
    uz: 'Boshqa housekeeping so‘rovi',
    ru: 'Другой запрос хаускипинга',
    en: 'Other Housekeeping Request',
  },
  'Hair Cut': { uz: 'Soch olish', ru: 'Стрижка', en: 'Hair Cut' },
  'Hair Styling': { uz: 'Soch turmagi', ru: 'Укладка волос', en: 'Hair Styling' },
  'Hair Wash & Blow': {
    uz: 'Soch yuvish va fen',
    ru: 'Мытьё и сушка волос',
    en: 'Hair Wash & Blow',
  },
  'Hair Coloring': { uz: 'Soch bo‘yash', ru: 'Окрашивание волос', en: 'Hair Coloring' },
  'Hair Treatment': { uz: 'Soch parvarishi', ru: 'Уход за волосами', en: 'Hair Treatment' },
  Manicure: { uz: 'Manikyur', ru: 'Маникюр', en: 'Manicure' },
  Pedicure: { uz: 'Pedikyur', ru: 'Педикюр', en: 'Pedicure' },
  'Nail Treatment': { uz: 'Tirnoq parvarishi', ru: 'Уход за ногтями', en: 'Nail Treatment' },
  'Makeup Service': { uz: 'Makiyaj xizmati', ru: 'Услуга макияжа', en: 'Makeup Service' },
  'Other Beauty & Salon Request': {
    uz: 'Boshqa go‘zallik va salon so‘rovi',
    ru: 'Другой запрос красоты и салона',
    en: 'Other Beauty & Salon Request',
  },
};

export function localizedMenuName(name: string): LocalizedText {
  const translation = MENU_NAME_TRANSLATIONS[name];
  if (translation !== undefined) return { ...translation };
  return { uz: name, ru: name, en: name };
}
